export const SALES_BOOK_VERSION = 2;

export const salesData = {
  암보험: {
    니즈환기: [
"/sales-book/암보험/니즈환기/1.png",
"/sales-book/암보험/니즈환기/2.png",
"/sales-book/암보험/니즈환기/3.png",
"/sales-book/암보험/니즈환기/4.png",
"/sales-book/암보험/니즈환기/5.png",
"/sales-book/암보험/니즈환기/6.png",
"/sales-book/암보험/니즈환기/7.png",
"/sales-book/암보험/니즈환기/8.png",
"/sales-book/암보험/니즈환기/9.png",
"/sales-book/암보험/니즈환기/10.png",
"/sales-book/암보험/니즈환기/11.png",
"/sales-book/암보험/니즈환기/12.png",
"/sales-book/암보험/니즈환기/13.png",
"/sales-book/암보험/니즈환기/14.png",
"/sales-book/암보험/니즈환기/15.png",
"/sales-book/암보험/니즈환기/16.png",
"/sales-book/암보험/니즈환기/17.png",
"/sales-book/암보험/니즈환기/18.png",
"/sales-book/암보험/니즈환기/19.png",
"/sales-book/암보험/니즈환기/20.png",
"/sales-book/암보험/니즈환기/21.png",
"/sales-book/암보험/니즈환기/22.png",
"/sales-book/암보험/니즈환기/23.png",
"/sales-book/암보험/니즈환기/24.png",
"/sales-book/암보험/니즈환기/25.png",
"/sales-book/암보험/니즈환기/26.png",
"/sales-book/암보험/니즈환기/27.png",
"/sales-book/암보험/니즈환기/28.png",

"/sales-book/암보험/니즈환기/29.png",
    ],

  },

  실손보험: {
    "실손 변천사": [
     
    ],

  },

운전자보험: {
  "운전자보험 설명서": [
"/sales-book/운전자보험/운전자보험 설명서/1.png",
"/sales-book/운전자보험/운전자보험 설명서/2.png",
"/sales-book/운전자보험/운전자보험 설명서/3.png",
"/sales-book/운전자보험/운전자보험 설명서/4.png",
"/sales-book/운전자보험/운전자보험 설명서/5.png",
"/sales-book/운전자보험/운전자보험 설명서/6.png",
"/sales-book/운전자보험/운전자보험 설명서/7.png",
"/sales-book/운전자보험/운전자보험 설명서/8.png",
"/sales-book/운전자보험/운전자보험 설명서/9.png",
"/sales-book/운전자보험/운전자보험 설명서/10.png",
"/sales-book/운전자보험/운전자보험 설명서/11.png",
"/sales-book/운전자보험/운전자보험 설명서/12.png",
"/sales-book/운전자보험/운전자보험 설명서/13.png",
"/sales-book/운전자보험/운전자보험 설명서/14.png",
"/sales-book/운전자보험/운전자보험 설명서/15.png",
"/sales-book/운전자보험/운전자보험 설명서/16.png",
"/sales-book/운전자보험/운전자보험 설명서/17.png",
"/sales-book/운전자보험/운전자보험 설명서/18.png",
"/sales-book/운전자보험/운전자보험 설명서/19.png",
"/sales-book/운전자보험/운전자보험 설명서/20.png",
"/sales-book/운전자보험/운전자보험 설명서/21.png",
"/sales-book/운전자보험/운전자보험 설명서/22.png",
"/sales-book/운전자보험/운전자보험 설명서/23.png",
"/sales-book/운전자보험/운전자보험 설명서/24.png",
"/sales-book/운전자보험/운전자보험 설명서/25.png",
"/sales-book/운전자보험/운전자보험 설명서/26.png",
"/sales-book/운전자보험/운전자보험 설명서/27.png",
"/sales-book/운전자보험/운전자보험 설명서/28.png",
"/sales-book/운전자보험/운전자보험 설명서/29.png",
"/sales-book/운전자보험/운전자보험 설명서/30.png",
"/sales-book/운전자보험/운전자보험 설명서/31.png",
"/sales-book/운전자보험/운전자보험 설명서/32.png",
  ],
},

니즈환기: {
  "노후준비": [
    "/sales-book/니즈환기/노후준비/1.png",
    "/sales-book/니즈환기/노후준비/2.png",
    "/sales-book/니즈환기/노후준비/3.png",
    "/sales-book/니즈환기/노후준비/4.png",
    "/sales-book/니즈환기/노후준비/5.png",
    "/sales-book/니즈환기/노후준비/6.png",
    "/sales-book/니즈환기/노후준비/7.png",
    "/sales-book/니즈환기/노후준비/8.png",
    "/sales-book/니즈환기/노후준비/9.png",
    "/sales-book/니즈환기/노후준비/10.png",
    "/sales-book/니즈환기/노후준비/11.png",
    "/sales-book/니즈환기/노후준비/12.png",
    "/sales-book/니즈환기/노후준비/13.png",
    "/sales-book/니즈환기/노후준비/14.png",
    "/sales-book/니즈환기/노후준비/15.png",
  ],
},
};