"use client";
import { useEffect, useState } from "react";
import { Pipette, X } from "lucide-react";
function rgbOf(hex:string){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));}
function hsvOf(hex:string){const [r,g,b]=rgbOf(hex).map(n=>n/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=60*((g-b)/d%6);else if(max===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4);}return {h:(h+360)%360,s:max?d/max:0,v:max};}
function hexOf(h:number,s:number,v:number){const c=v*s,x=c*(1-Math.abs(h/60%2-1)),m=v-c;const channels=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return '#'+channels.map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('');}
export default function DesktopMemoColorPicker({value,onChange,onClose}:{value:string;onChange:(color:string)=>void;onClose:()=>void}){
 const hsv=hsvOf(value),[hue,setHue]=useState(hsv.h),[notice,setNotice]=useState(''),[draft,setDraft]=useState(rgbOf(value).map(String));
 useEffect(()=>{setDraft(rgbOf(value).map(String));const next=hsvOf(value);if(next.s>0)setHue(next.h);},[value]);
 async function eyedrop(){const Dropper=(window as unknown as {EyeDropper?:new()=>{open:()=>Promise<{sRGBHex:string}>}}).EyeDropper;if(!Dropper){setNotice('이 브라우저는 스포이트를 지원하지 않습니다.');return;}try{onChange((await new Dropper().open()).sRGBHex);}catch{}}
 return <div className="bg-white border border-gray-200 rounded-xl p-3 shadow-xl"><div className="flex justify-between items-center mb-2"><span className="text-xs font-semibold">글자색</span><button type="button" aria-label="색상 선택 닫기" onClick={onClose} className="cursor-pointer text-slate-400"><X className="w-4 h-4"/></button></div><div className="relative h-44 touch-none cursor-crosshair border border-gray-200" role="slider" aria-label="채도와 밝기" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(hsv.v*100)} tabIndex={0} style={{background:`linear-gradient(to top,black,transparent),linear-gradient(to right,white,hsl(${hue},100%,50%))`}} onPointerDown={e=>{const area=e.currentTarget,rect=area.getBoundingClientRect();area.setPointerCapture(e.pointerId);const choose=(x:number,y:number)=>onChange(hexOf(hue,Math.max(0,Math.min(1,(x-rect.left)/rect.width)),1-Math.max(0,Math.min(1,(y-rect.top)/rect.height))));choose(e.clientX,e.clientY);area.onpointermove=v=>choose(v.clientX,v.clientY);const stop=()=>{area.onpointermove=null;area.onpointerup=null;area.onpointercancel=null;};area.onpointerup=stop;area.onpointercancel=stop;}} onKeyDown={e=>{if(e.key.startsWith('Arrow')){e.preventDefault();onChange(hexOf(hue,Math.max(0,Math.min(1,hsv.s+(e.key==='ArrowRight'?.02:e.key==='ArrowLeft'?-.02:0))),Math.max(0,Math.min(1,hsv.v+(e.key==='ArrowUp'?.02:e.key==='ArrowDown'?-.02:0)))));}}}><span className="absolute w-3 h-3 rounded-full border-2 border-white shadow pointer-events-none -translate-x-1/2 -translate-y-1/2" style={{left:`${hsv.s*100}%`,top:`${(1-hsv.v)*100}%`}}/></div><div className="flex gap-3 items-center my-3"><button type="button" onClick={eyedrop} aria-label="스포이트" className="cursor-pointer"><Pipette className="w-4 h-4"/></button><span className="w-7 h-7 rounded-full border border-gray-200 shrink-0" style={{background:value}}/><input type="range" min={0} max={359} value={Math.round(hue)} aria-label="색조" onChange={e=>{const h=Number(e.target.value);setHue(h);onChange(hexOf(h,hsv.s||1,hsv.v||1));}} className="memo-hue-slider flex-1 min-w-0"/></div><div className="grid grid-cols-3 gap-2">{['R','G','B'].map((channel,i)=><label key={channel} className="text-center text-xs"><input data-ui-field="true" type="number" min={0} max={255} aria-label={`${channel} 색상 값`} value={draft[i]} onChange={e=>{const raw=e.target.value;setDraft(d=>d.map((v,j)=>j===i?raw:v));if(raw!==''&&Number.isFinite(Number(raw))){const rgb=rgbOf(value);rgb[i]=Math.max(0,Math.min(255,Math.round(Number(raw))));onChange('#'+rgb.map(n=>n.toString(16).padStart(2,'0')).join(''));}}} onBlur={()=>setDraft(rgbOf(value).map(String))} className="w-full h-8 border border-gray-200 rounded px-1 text-center text-sm mb-1"/>{channel}</label>)}</div>{notice&&<p className="text-xs text-slate-500 mt-2">{notice}</p>}</div>;
}
