"use client";
import { useState } from "react";
import { NotebookPen, Plus, Search, Pin, Eye, Trash2 } from "lucide-react";
import { useAuth } from "../AuthProvider";
import { decodeMemo, memoBackground, type MemoItem } from "@/lib/memos/model";
import MemoBody from "./MemoBody";
import MemoEditor from "./MemoEditor";
export default function MemoBoard() {
 const { memos, persistMemos, memosLoading, memosError, reloadMemos } = useAuth();
 const [search,setSearch]=useState("");
 const [editing,setEditing]=useState<MemoItem|null|undefined>(undefined),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 async function update(id:string,patch:Partial<MemoItem>, reject=false) { if(busy) { if(reject) throw new Error("busy"); return; } setBusy(true); try { await persistMemos(memos.map(m=>m.id===id?{...m,...patch,updatedAt:new Date().toISOString()}:m)); setNotice(""); } catch {setNotice("변경 내용을 저장하지 못했습니다."); if(reject) throw new Error("save failed");} finally{setBusy(false);} }
 async function remove(id:string) { if(busy || !window.confirm("이 메모를 삭제하시겠습니까?")) return; setBusy(true); try { await persistMemos(memos.filter(m=>m.id!==id)); setNotice(""); } catch { setNotice("메모를 삭제하지 못했습니다."); } finally { setBusy(false); } }
 const shown=memos.filter(m=>`${m.title} ${decodeMemo(m).text}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||(Date.parse(b.updatedAt)||0)-(Date.parse(a.updatedAt)||0));
 return <section className="memo-board space-y-4">
 <div className="flex flex-wrap items-center justify-between gap-4"><h2 className="flex items-center gap-3 text-xl font-bold"><NotebookPen className="w-7 h-7 text-yellow-500"/>메모</h2><div className="flex w-full sm:w-[520px] max-w-full items-center gap-3"><label className="flex min-w-0 items-center gap-2 bg-white border border-gray-200 rounded-xl px-3 h-11 flex-1 focus-within:border-yellow-400"><Search className="w-4 h-4 shrink-0 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="메모 검색 (제목, 내용)" aria-label="메모 검색" className="min-w-0 w-full h-full text-sm text-gray-900 caret-gray-900 cursor-text outline-none"/></label><button disabled={memosLoading||!!memosError||busy} onClick={()=>setEditing(null)} className="flex items-center gap-2 rounded-xl bg-yellow-400 px-4 h-11 text-sm font-bold whitespace-nowrap cursor-pointer disabled:opacity-50"><Plus className="w-5 h-5"/>새 메모</button></div></div>
 
 {memosLoading&&<p className="py-8 text-center text-sm text-slate-500">메모를 불러오는 중입니다.</p>}{memosError&&<p role="alert" className="text-sm text-red-500">{memosError}<button onClick={reloadMemos} className="ml-3 underline cursor-pointer">다시 시도</button></p>}{notice&&<p role="alert" className="text-sm text-red-500">{notice}</p>}
 <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">{shown.map(m=>{const d=decodeMemo(m);return <article key={m.id} tabIndex={0} aria-label={`${m.title || "제목 없는 메모"} 수정`} onDoubleClick={e=>{if(!busy && !(e.target as HTMLElement).closest("button, li[data-list]"))setEditing(m);}} onKeyDown={e=>{if(e.key==="Enter" && e.target===e.currentTarget && !busy){e.preventDefault();setEditing(m);}}} className="relative rounded-2xl border border-slate-200/70 shadow-sm p-5 flex flex-col min-h-52" style={{background:memoBackground(d)}}><div className="flex items-start justify-between gap-2"><h3 className="text-left font-bold text-base break-words">{m.title||"제목 없는 메모"}</h3><div className="flex items-center gap-2 shrink-0"><button disabled={busy} aria-label={m.pinned?"고정 해제":"메모 고정"} onClick={()=>update(m.id,{pinned:!m.pinned})} className={`cursor-pointer ${m.pinned?"text-red-500":"text-slate-300"}`}><Pin className="w-4 h-4"/></button><button disabled={busy} aria-label={m.visible?"메모 화면에서 숨기기":"메모 화면에 표시"} aria-pressed={m.visible} title={m.visible?"화면에서 숨기기":"화면에 표시"} onClick={()=>update(m.id,{visible:!m.visible})} className={`cursor-pointer ${m.visible?"text-blue-600":"text-slate-300"}`}><Eye className="w-4 h-4"/></button></div></div><div className="mt-3 flex-1 max-h-48 overflow-y-auto"><MemoBody memo={m} onChange={content=>update(m.id,{content},true)}/></div><div className="flex items-center justify-between mt-2 text-xs text-slate-400"><time>{m.updatedAt?new Date(m.updatedAt).toLocaleString("ko-KR",{year:"numeric",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}):""}</time><button disabled={busy} aria-label="메모 삭제" title="메모 삭제" onClick={()=>void remove(m.id)} className="p-1 cursor-pointer hover:text-red-500 disabled:opacity-40"><Trash2 className="w-4 h-4"/></button></div></article>})}{!memosLoading&&!memosError&&<button disabled={busy} onClick={()=>setEditing(null)} className="min-h-52 rounded-2xl border border-dashed border-slate-300 flex flex-col items-center justify-center gap-3 text-slate-500 cursor-pointer"><Plus className="w-7 h-7"/><span className="font-semibold">새 메모</span></button>}</div>
 {editing!==undefined&&<MemoEditor key={editing?.id||"new"} memo={editing} onClose={()=>setEditing(undefined)}/>}
 </section>;
}
