"use client";
import { useEffect, useId, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Check, ChevronDown } from "lucide-react";
export default function MemoSelect({value,onChange,options,label,disabled=false}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string;disabled?:boolean}){
 const id=useId(),button=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null);const [pos,setPos]=useState<{top:number;left:number;width:number}|null>(null),[index,setIndex]=useState(0);
 const close=()=>{setPos(null);button.current?.focus();};
 function open(){const r=button.current!.getBoundingClientRect();const height=options.length*38+8;setPos({top:r.bottom+height>window.innerHeight?r.top-height-4:r.bottom+4,left:Math.max(8,Math.min(r.left,window.innerWidth-Math.max(r.width,110)-8)),width:Math.max(r.width,110)});setIndex(Math.max(0,options.findIndex(o=>o.value===value)));}
 useEffect(()=>{if(!pos)return;menu.current?.focus();const outside=(e:PointerEvent)=>{if(!menu.current?.contains(e.target as Node)&&!button.current?.contains(e.target as Node))setPos(null);};const layout=()=>setPos(null);document.addEventListener("pointerdown",outside);window.addEventListener("resize",layout);window.addEventListener("scroll",layout,true);return()=>{document.removeEventListener("pointerdown",outside);window.removeEventListener("resize",layout);window.removeEventListener("scroll",layout,true);};},[pos]);
 return <><button ref={button} type="button" disabled={disabled} aria-label={label} aria-haspopup="listbox" aria-expanded={!!pos} aria-controls={pos?id:undefined} onClick={()=>pos?close():open()} onKeyDown={e=>{if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();open();}}} className="inline-flex items-center justify-between gap-2 h-8 px-3 bg-white border border-gray-200 rounded-lg text-xs font-medium cursor-pointer disabled:opacity-50">{options.find(o=>o.value===value)?.label}<ChevronDown className="w-3.5 h-3.5 text-slate-400"/></button>{pos&&createPortal(<div ref={menu} id={id} tabIndex={-1} role="listbox" aria-label={label} aria-activedescendant={`${id}-${index}`} className="fixed z-[7200] bg-white border border-gray-200 rounded-xl shadow-xl p-1 outline-none" style={pos} onClick={e=>e.stopPropagation()} onKeyDown={e=>{e.stopPropagation();if(e.key==="Escape"){e.preventDefault();close();}if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();setIndex(i=>(i+(e.key==="ArrowDown"?1:-1)+options.length)%options.length);}if(e.key==="Enter"||e.key===" "){e.preventDefault();onChange(options[index].value);close();}if(e.key==="Tab")setPos(null);}}>{options.map((o,i)=><button key={o.value} id={`${id}-${i}`} type="button" role="option" aria-selected={o.value===value} tabIndex={-1} onMouseEnter={()=>setIndex(i)} onClick={()=>{onChange(o.value);close();}} className={`flex items-center justify-between gap-4 w-full px-3 py-2 text-xs rounded-lg cursor-pointer ${index===i?"bg-blue-50 text-blue-600":"text-slate-600"}`}>{o.label}{o.value===value&&<Check className="w-3.5 h-3.5"/>}</button>)}</div>,document.body)}</>;
}
